### ISSUE TITLE
Issue in conversion to BDD100K format

### ISSUE THREAD

**Issue by Raspberry-beans** [ethvis/qd-track#139]
Hi,
I have got the prediction file (.pkl) after using `tools/test.py` . Now I want to convert predictions into BDD100K format, but receiving the error listed below. Any suggestions would be appreciated.

Command given : 

`python tools/to_bdd100k.py /HOMES/rehman/models/qdtrack/qdtrack/configs/bdd100k/qdtrack-frcnn_r50_fpn_12e_bdd100k.py --res /HOMES/rehman/models/qdtrack/qdtrack/results/result.pkl --task box_track --bdd-dir /HOMES/rehman/models/qdtrack/qdtrack/bdd_track_result/ --nproc 4
`

Error received:
```

loading annotations into memory...
Done (t=2.04s)
creating index...
index created!

Loading results from /HOMES/rehman/models/qdtrack/qdtrack/results/result.pkl

Start converting to BDD100K box tracking format
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/HOMES/rehman/models/qdtrack/qdtrack/tools/to_bdd100k.py", line 76, in <module>
    main()
  File "/HOMES/rehman/models/qdtrack/qdtrack/tools/to_bdd100k.py", line 67, in main
    preds2bdd100k(
  File "/HOMES/rehman/models/qdtrack/qdtrack/qdtrack/core/to_bdd100k/transforms.py", line 139, in preds2bdd100k
    metric2func[task](dataset, results, out_base, *args, **kwargs)
  File "/HOMES/rehman/models/qdtrack/qdtrack/qdtrack/core/to_bdd100k/transforms.py", line 101, in box_track_to_bdd100k
    for id_, instance in track_dict.items():
AttributeError: 'list' object has no attribute 'items'

```

**Comment by damengyua** [comment]
I also encountered this problem. How did you solve it?
